apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: video-app
data:
  # Database
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app_db"
  DB_LOGGING: "true"
  
  # Kafka (3 brokers)
  KAFKA_BROKERS: "kafka-1:19092,kafka-2:19092,kafka-3:19092"
  MINIO_KAFKA_TOPIC: "upload-video"
  
  # MinIO
  MINIO_URL: "http://minio:9000"
  MINIO_PUBLIC_URL: "http://localhost:9000"
  BUCKET_VIDEO_NAME: "video"
  BUCKET_SCREENSHOT_NAME: "screenshot"
  BUCKET_REGION: "us-east-1"
  
  # Redis
  REDIS_URL: "redis://redis:6379"
  
  # App Config
  NODE_ENV: "development"
  MAX_FILE_SIZE_MB: "10"
