name: CI - api-bff

on:
  push:
    paths:
      - "projects/api-bff/**"
  pull_request:
    paths:
      - "projects/api-bff/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: projects/api-bff/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: projects/api-bff

      - name: Run tests
        run: npm run test:cov
        working-directory: projects/api-bff
